In [23]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [24]:
import numpy as np
np.set_printoptions(precision=3)

In [4]:
a = np.array([1,2,3], dtype = np.int32) #mảng của numpy
b = [4, 5, 6] # Mảng của python
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

In [5]:
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
tf.is_tensor(a)

False

In [7]:
tf.is_tensor(t_a)

True

In [8]:
tf.is_tensor(t_b)

True

In [9]:
t_ones = tf.ones((2,3))
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
const_tensor = tf.constant([1, 2.12, np.pi], dtype = tf.float32)

In [12]:
tf.fill((2, 3), 1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [15]:
t_a_new = tf.cast(t_a, dtype = tf.int64)

In [16]:
t = tf.random.uniform(shape= (3,5))

In [17]:
t

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.919, 0.904, 0.059, 0.924, 0.601],
       [0.721, 0.367, 0.084, 0.167, 0.961],
       [0.968, 0.241, 0.737, 0.654, 0.106]], dtype=float32)>

In [18]:
t_tr = tf.transpose(t)
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.919, 0.721, 0.968],
       [0.904, 0.367, 0.241],
       [0.059, 0.084, 0.737],
       [0.924, 0.167, 0.654],
       [0.601, 0.961, 0.106]], dtype=float32)>

In [19]:
t = tf.zeros((30,))

In [22]:
t_reshape = tf.reshape(t, shape=(5,6))

In [25]:
a = [1.2, 3.4, 5.6, 7.8, 9.0]
ds = tf.data.Dataset.from_tensor_slices(a)

In [26]:
for item in ds:
  print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(5.6, shape=(), dtype=float32)
tf.Tensor(7.8, shape=(), dtype=float32)
tf.Tensor(9.0, shape=(), dtype=float32)


In [28]:
ds_batch = ds.batch(3)
for i, element in enumerate(ds_batch, 100):
  print(element)

tf.Tensor([1.2 3.4 5.6], shape=(3,), dtype=float32)
tf.Tensor([7.8 9. ], shape=(2,), dtype=float32)
