In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.18.0'

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3], dtype = np.int32)
b = [4, 5, 6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [6]:
tf.is_tensor(t_a)

True

In [7]:
tf.is_tensor(t_b)

True

In [8]:
tf.is_tensor(a)

False

In [9]:
t_one = tf.ones((2, 3 ))
t_one.shape

TensorShape([2, 3])

In [10]:
t_one.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
t_const = tf.constant([2, 3, np.pi], dtype = np.float32)

In [12]:
print(t_const)

tf.Tensor([2.        3.        3.1415927], shape=(3,), dtype=float32)


In [13]:
t_fill = tf.fill((2,3,4), 4)

In [14]:
print(t_fill)

tf.Tensor(
[[[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]

 [[4 4 4 4]
  [4 4 4 4]
  [4 4 4 4]]], shape=(2, 3, 4), dtype=int32)


In [15]:
t_fill = tf.fill((2,3,4,5), 5)

In [16]:
print(t_fill)

tf.Tensor(
[[[[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]

  [[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]

  [[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]]


 [[[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]

  [[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]

  [[5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]
   [5 5 5 5 5]]]], shape=(2, 3, 4, 5), dtype=int32)


In [17]:
tf.cast(t_a, dtype = tf.int64)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [18]:
t_zeros = tf.zeros((30,))
print(t_zeros)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)


In [19]:
t_tran = tf.reshape(t_zeros, shape = (5,6))
print(t_tran)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [20]:
t = tf.zeros((1,2,1,4,1))
print(t)
t_sqz= tf.squeeze(t, axis = (2, 4))
print(t_sqz)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2, 4), dtype=float32)


In [21]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape = (5,2), minval = -1, maxval = 1)
t2 = tf.random.normal(shape = (5,2), mean = 0.0, stddev = 1.0)
print(t1, t2)

tf.Tensor(
[[-0.6697383   0.80296254]
 [ 0.26194835 -0.13090777]
 [-0.41612196  0.28500414]
 [ 0.951571   -0.12980103]
 [ 0.32020378  0.20979166]], shape=(5, 2), dtype=float32) tf.Tensor(
[[ 0.40308788 -1.0880208 ]
 [-0.06309535  1.3365567 ]
 [ 0.7117601  -0.48928645]
 [-0.7642213  -1.0372486 ]
 [-1.2519338   0.02122428]], shape=(5, 2), dtype=float32)


In [22]:
t3 = tf.multiply(t1, t2).numpy()
print(t3)

[[-0.26996338 -0.87363994]
 [-0.01652772 -0.17496566]
 [-0.296179   -0.13944866]
 [-0.7272108   0.13463594]
 [-0.40087393  0.00445268]]


In [23]:
t4 = tf.math.reduce_mean(t1, axis = 0)
print(t4)

tf.Tensor([0.08957257 0.2074099 ], shape=(2,), dtype=float32)


In [24]:
t5 = tf.linalg.matmul(t1, t2, transpose_b = True)
print(t5.numpy())

[[-1.1436033   1.1154624  -0.8695717  -0.3210435   0.8555103 ]
 [ 0.2480186  -0.19149339  0.2504958  -0.0644026  -0.3307204 ]
 [-0.47782415  0.40717956 -0.43562764  0.02238911  0.5270062 ]
 [ 0.52479297 -0.23352614  0.74080014 -0.5925749  -1.1940588 ]
 [-0.09918742  0.26019508  0.12526006 -0.46231267 -0.39642125]]


In [25]:
t6 = tf.linalg.matmul(t1, t2, transpose_a = True)
print(t6.numpy())

[[-1.7107549   0.30218127]
 [ 0.37133017 -1.0489656 ]]


In [26]:
print(t1)
norm_t1 = tf.norm(t1, ord = 2, axis = 1).numpy()
print(norm_t1)

tf.Tensor(
[[-0.6697383   0.80296254]
 [ 0.26194835 -0.13090777]
 [-0.41612196  0.28500414]
 [ 0.951571   -0.12980103]
 [ 0.32020378  0.20979166]], shape=(5, 2), dtype=float32)
[1.045609   0.29283747 0.5043658  0.9603831  0.38280934]


In [27]:
norm_t1 = np.sqrt(np.sum(np.square(t1.numpy()), axis = 1))
print(norm_t1)

[1.045609   0.29283747 0.5043658  0.9603831  0.38280934]


In [28]:
t1 @ tf.transpose(t2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.1436033 ,  1.1154624 , -0.8695717 , -0.3210435 ,  0.8555103 ],
       [ 0.2480186 , -0.19149339,  0.2504958 , -0.0644026 , -0.3307204 ],
       [-0.47782415,  0.40717956, -0.43562764,  0.02238911,  0.5270062 ],
       [ 0.52479297, -0.23352614,  0.74080014, -0.5925749 , -1.1940588 ],
       [-0.09918742,  0.26019508,  0.12526006, -0.46231267, -0.39642125]],
      dtype=float32)>

In [29]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())
t_splits = tf.split(t, 3)
[item.numpy() for item in t_splits]

[0.16513085 0.9014813  0.6309742  0.4345461  0.29193902 0.64250207]


[array([0.16513085, 0.9014813 ], dtype=float32),
 array([0.6309742, 0.4345461], dtype=float32),
 array([0.29193902, 0.64250207], dtype=float32)]

In [30]:
A = tf.zeros((3,))
B = tf.ones((2,))
C = tf.concat([A, B], axis = 0) #Nối song song
print(C.numpy())

[0. 0. 0. 1. 1.]


In [31]:
A = tf.zeros((3,))
B = tf.ones((3,))
C = tf.stack([A, B], axis = 0)
print(C.numpy())

[[0. 0. 0.]
 [1. 1. 1.]]


In [32]:
a = [1.2, 3.4, 5.6, 7.8, 9.1, 4.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>


In [33]:
for item in ds:
  print(item.numpy())

1.2
3.4
5.6
7.8
9.1
4.0


In [34]:
ds_batch = ds.batch(3)
for i, elem in enumerate(ds_batch, 100):
  print("batch {}".format(i), elem.numpy())

batch 100 [1.2 3.4 5.6]
batch 101 [7.8 9.1 4. ]


In [36]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype = tf.float32)
t_y = tf.range(4)
print(t_x)
print(t_y)

tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]
 [0.60489583 0.6366315  0.6144488 ]], shape=(4, 3), dtype=float32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [38]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)

ds_joint = tf.data.Dataset.zip((ds_x, ds_y)) #Tạo thành 1 tuple
for example in ds_joint:
  print("x: ", example[0].numpy(),
        "y: ", example[1].numpy())

x:  [0.16513085 0.9014813  0.6309742 ] y:  0
x:  [0.4345461  0.29193902 0.64250207] y:  1
x:  [0.9757855  0.43509948 0.6601019 ] y:  2
x:  [0.60489583 0.6366315  0.6144488 ] y:  3


In [39]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(buffer_size = len(t_x))

for example in ds:
  print("x: ", example[0].numpy(),
  "y: ", example[1].numpy())

x:  [0.9757855  0.43509948 0.6601019 ] y:  2
x:  [0.4345461  0.29193902 0.64250207] y:  1
x:  [0.16513085 0.9014813  0.6309742 ] y:  0
x:  [0.60489583 0.6366315  0.6144488 ] y:  3


In [42]:
ds = ds_joint.batch(batch_size = 2, drop_remainder = False)
batch_x, batch_y = next(iter(ds))
for example in ds:
  print("x: ", example[0].numpy(),
        "y: ", example[1].numpy())

x:  [[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]] y:  [0 1]
x:  [[0.9757855  0.43509948 0.6601019 ]
 [0.60489583 0.6366315  0.6144488 ]] y:  [2 3]


In [43]:
ds = ds_joint.batch(3).repeat(count =2)

for i,(batch_x, batch_y) in enumerate(ds):
  print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (1, 3) [3]
2 (3, 3) [0 1 2]
3 (1, 3) [3]


In [44]:
ds = ds_joint.repeat(count=2).batch(3)
for i, (batch_x, batch_y) in enumerate(ds):
  print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (3, 3) [3 0 1]
2 (2, 3) [2 3]


In [45]:
#shuffle=>batch=>repeat
ds = ds_joint.shuffle(4).batch(3).repeat(2)
for i, (batch_x, batch_y) in enumerate(ds):
  print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [1 2 3]
1 (1, 3) [0]
2 (3, 3) [1 3 0]
3 (1, 3) [2]
